require: rubocop-rails

# Common configuration.
AllCops:
  NewCops: disable
  TargetRubyVersion: 2.6
  Exclude:
    - !ruby/regexp /.*solano.*\.rb$/
    - !ruby/regexp /.*tddium.*\.rb$/
    - bin/**/*
    - client/**/*
    - config/boot.rb
    - rgloader/loader.rb
    - script/**/*
    - vendor/**/*

#################### Layout ################################

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 120
  # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
  # directives like '# rubocop: enable ...' when calculating a line's length.
  IgnoreCopDirectives: true
  Exclude:
    - config/routes.rb # Annotations run long.
    - db/**/*

#################### Style #################################

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

Style/RegexpLiteral:
  Enabled: false

#################### Naming ################################

Naming/FileName:
  Enabled: false

#################### Metrics ###############################

Metrics/AbcSize:
  Max: 22.5
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
  - config/routes.rb
  - app/views/api/**/*
  - db/**/*

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15
  Exclude:
    - db/**/*

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 10

#################### Lint ##################################

Lint/AmbiguousBlockAssociation:
    Exclude:
    - spec/**/*

Lint/SymbolConversion:
  EnforcedStyle: consistent

#################### Rails #################################

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - spec/**/*
    - db/**/*

Rails/ApplicationRecord:
  Exclude:
    - db/**/*
